name: CI

on:
  push:
    branches:
      - master
      - main
      - 'v*-branch'
  pull_request:
    branches:
      - master
      - main
      - 'v*-branch'

jobs:
  ci:
    uses: humanmade/altis-dev-tools/.github/workflows/module-ci.yml@088bce7321fde60b9c22e792e764fa13ccd8f6ab
    with:
      altis-package: altis/cms
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
